version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: event-mongo
    ports:
      - "27018:27017"
    networks:
      - event-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./volumes/mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  gateway-server:
    build:
      context: ./apps/gateway-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - event-network
    depends_on:
      - mongodb
      - auth-server
      - event-server
    env_file:
      - .env

  auth-server:
    build:
      context: ./apps/auth-server
      dockerfile: Dockerfile
    networks:
      - event-network
    depends_on:
      - mongodb
    env_file:
      - apps/auth-server/.env

  event-server:
    build:
      context: apps/event-server
      dockerfile: Dockerfile
    networks:
      - event-network
    depends_on:
      - mongodb
    env_file:
      - apps/event-server/.env

networks:
  event-network:
    driver: bridge
